### ISSUE TITLE
Mudar a foto do "Sobre o Grupo"

### ISSUE THREAD

**Issue by rgmantovani** [ic2d/ic2d.github.io#2]
Trocar a foto dos jovens fazendo joinha hahaha

**Comment by WPitombeira** [comment]
Coloquei a foto genérica para "ilustração", acredito que ficaria interessante adicionarmos uma foto do grupo quando pudermos nos reunir presencialmente.

Removi a imagem dos jovens, caso tenham alguma sugestão de imagem a ser colocada no lugar, basta entrar em contato que substituo e libero novamente.
